### ISSUE TITLE
Stage Packages tab missing from Snowflake Notebooks package import dialog

### ISSUE THREAD

**Issue by dwelden** [Snowflake-Labs/snowflake-demo-notebooks#31]
Per documentation [Import Packages from a Snowflake Stage](https://docs.snowflake.com/en/user-guide/ui-snowsight/notebooks-import-packages#import-packages-from-a-snowflake-stage), there should be a tab for Stage Packages. That tab does not appear in my corporate account.  

![image](https://github.com/Snowflake-Labs/snowflake-demo-notebooks/assets/11447810/61b93519-a17d-4857-9eb5-b3a02c262645)

**Comment by natalieintveld** [comment]
I am having the same problem.

**Comment by sfc-gh-dolee** [comment]
Thanks for reporting this @dwelden @natalieintveld. Import package from stage is a private preview feature and support for this feature is currently not in production and is available only to selected accounts. We've updated the documentation and examples to reflect this.

**Comment by natalieintveld** [comment]
Thank you Doris for your reply!


Met vriendelijke groet,
Natalie in ’t Veld

06-4214 6944
***@***.***
www.pieceofdata.nl<http://www.pieceofdata.nl>

***@***.***

Van: Doris Lee ***@***.***>
Verzonden: woensdag 26 juni 2024 16:41
Aan: Snowflake-Labs/snowflake-demo-notebooks ***@***.***>
CC: Natalie in 't Veld ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Snowflake-Labs/snowflake-demo-notebooks] Stage Packages tab missing from Snowflake Notebooks package import dialog (Issue #31)


Thanks for reporting this @dwelden<https://github.com/dwelden> @natalieintveld<https://github.com/natalieintveld>. Import package from stage is a private preview feature and support for this feature is currently not in production and is available only to selected accounts. We've updated the documentation and examples to reflect this.
