### ISSUE TITLE
Update instruction for notebook: Import Package from Stage

### ISSUE THREAD

**Issue by sashamitrovich** [Snowflake-Labs/snowflake-demo-notebooks#36]
On the "Upload the package using the Package Picker UI" step the instructions are as follow:
> Now that the simple.zip package is on the stage, we can specify the path to this package in the Package Picker.
>
> Click on the Packages dropdown
> Navigate to Stage Packages tab
> Enter the Stage Package Path as: @MY_PACKAGES/simple.zip_
Running cell
`import simple`
Returns error:
`ModuleNotFoundError: Line 1: Module Not Found: simple. To import packages from Anaconda, install them first using the package selector at the top of the page.
`
In order to fix the issue, the instructions should be updated as per below:
The last step "Enter the Stage Package Path as" should be
Enter the Stage Package Path as (all lowercase): @<database>.<schema>.my_packages/simple.zip where <database>.<schema> is the actual namespace of the stage

**Comment by sfc-gh-dolee** [comment]
Thanks @sashamitrovich! This is fixed now.
